### ISSUE TITLE
mvn build fails with unresolved dependencies

### ISSUE THREAD

**Issue by ManfredSchenkIOSB** [avicomp/ont-d2rq#17]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ont-d2rq 1.0.5-SNAPSHOT ............................ SUCCESS [  0.206 s]
[INFO] d2rq-api ........................................... FAILURE [01:30 min]
[INFO] d2rq-tools 1.0.5-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:30 min
[INFO] Finished at: 2019-04-03T14:13:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project d2rq-api: Could not resolve dependencies for project ru.avicomp:d2rq-api:jar:1.0.5-SNAPSHOT: Could not find artifact com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.12.1 in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :d2rq-api

**Comment by sszuev** [comment]
It is strange. 
I just tried from scratch (after git clone) the command `mvn clean package` on two machines: everything works fine. 
The first : maven 3.3.3 + java 10, the second -  Maven 3.6.0 + java8. 

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ont-d2rq 1.0.5-SNAPSHOT:
[INFO]
[INFO] ont-d2rq ........................................... SUCCESS [  0.172 s]
[INFO] d2rq-api ........................................... SUCCESS [ 15.200 s]
[INFO] d2rq-tools ......................................... SUCCESS [  3.963 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.459 s
[INFO] Finished at: 2019-04-03T15:07:43+02:00
[INFO] ------------------------------------------------------------------------

G:\work\ont-d2rq>mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:4
7+02:00)
```
The error is also strange: jsonld-java is in dependencies of jena-arq, no other direct dependencies. 
And it is not jitpack package.

I suggest you to try several options: 
- delete jsonld-java from local maven dir (although the problem does not seem to be in jsonld)
- update maven
- try to build jena-arq itself to make sure everything is ok with it
- modify pom to get rid of jitpack, which is used only in test-scope for [ont-map](https://github.com/avicomp/ont-map) - you can just replace it with local installed ont-map, or even exclude it at all with disabling corresponding tests

I think, the root problem is in jitpack or interaction with jitpack.
I just tried a dummy project with `com.github.avicomp:ont-d2rq:1.0.4-SNAPSHOT` in dependencies 
and I got other failure: it cannot even get jar from jitpack.
Maybe I need to create new 1.0.5-SNAPSHOT pre-release for this case. 
Or it is temporary problems with jitpack server.

**Comment by ManfredSchenkIOSB** [comment]
Thanks for your fast reply.

Before creating the issue I had deleted my local maven Repo completely.
My current environment is Java8 (Oracle JDK) + Maven 3.5.4. on Windows10

I'll try again tomorrow...

**Comment by sszuev** [comment]
-  quick google shows that the problem is most likely due to bad naming of jsonld-java, that causes a conflict between repos. A lot of people has the same issue. And here is a possible solution: https://github.com/RMLio/rmlmapper-java/pull/19#issuecomment-459396129

- the `com.github.avicomp:ont-d2rq:1.0.4-SNAPSHOT` artifact building was really failed, and the error is exactly the same as reported, see [jitpack-logs](https://jitpack.io/com/github/avicomp/ont-d2rq/1.0.4-SNAPSHOT/build.log). 
But it has green status: https://jitpack.io/#avicomp/ont-d2rq, so I didn't noticed that.

**Comment by sszuev** [comment]
fixed. 
new pre-release is created: https://github.com/avicomp/ont-d2rq/releases/tag/1.0.5-SNAPSHOT
